"""Pro-mode infrastructure fixtures — add this to your conftest.py.

Generated by vibe-rescue. Customize the # ADAPT: sections for your service.
"""
import os
import pytest


# ---------------------------------------------------------------------------
# --pro-mode infrastructure: pytest hooks + real connection fixtures
# ---------------------------------------------------------------------------

def pytest_addoption(parser):
    parser.addoption(
        "--pro-mode", action="store_true", default=False,
        help="Run infrastructure validation tests against real Docker services",
    )
    parser.addoption(
        "--all-services", action="store_true", default=False,
        help="Also start dependent services for cross-service E2E tests",
    )


def pytest_configure(config):
    config.addinivalue_line("markers", "infra: requires Docker infrastructure (--pro-mode)")
    config.addinivalue_line("markers", "infra_postgres: requires PostgreSQL connection")
    config.addinivalue_line("markers", "infra_clickhouse: requires ClickHouse connection")
    config.addinivalue_line("markers", "infra_kafka: requires Kafka broker")


def pytest_collection_modifyitems(config, items):
    if config.getoption("--pro-mode"):
        return
    skip_infra = pytest.mark.skip(reason="needs --pro-mode to run infrastructure tests")
    for item in items:
        if "infra" in item.keywords:
            item.add_marker(skip_infra)


# ---------------------------------------------------------------------------
# Session-scoped connection fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def pg_engine():
    """Sync SQLAlchemy engine for schema introspection.

    # ADAPT: Change the env var name and default URL to match your service's
    # primary PostgreSQL database.
    """
    url = os.environ.get(
        "POSTGRES_DATABASE_URL",  # ADAPT: your service's PG connection env var
        "postgresql://ucp_user:ucp_local@localhost:5432/your_database",  # ADAPT: default
    )
    url = url.replace("postgresql://", "postgresql+psycopg2://", 1)
    try:
        from sqlalchemy import create_engine
        engine = create_engine(url, pool_pre_ping=True)
        engine.connect().close()
        return engine
    except Exception as exc:
        pytest.skip(f"PostgreSQL not reachable: {exc}")


@pytest.fixture(scope="session")
def ch_client():
    """Sync ClickHouse client for schema introspection.

    # ADAPT: Change env var names and database to match your service.
    """
    host = os.environ.get("CLICKHOUSE_HOST", "localhost")  # ADAPT: env var name
    port = int(os.environ.get("CLICKHOUSE_PORT", "9000"))  # ADAPT: env var name
    user = os.environ.get("CLICKHOUSE_USERNAME", "default")  # ADAPT: env var name
    password = os.environ.get("CLICKHOUSE_PASSWORD", "")  # ADAPT: env var name
    try:
        from clickhouse_driver import Client
        client = Client(
            host=host, port=port, user=user, password=password,
            database="ccp_ril",  # ADAPT: your ClickHouse database name
        )
        client.execute("SELECT 1")
        return client
    except Exception as exc:
        pytest.skip(f"ClickHouse not reachable: {exc}")


@pytest.fixture(scope="session")
def kafka_admin():
    """KafkaAdminClient for topic introspection.

    # ADAPT: Change the env var name to match your service's Kafka broker config.
    """
    brokers = os.environ.get(
        "KDC_KAFKA_BROKER_LIST",  # ADAPT: your broker list env var
        "localhost:9092",
    )
    try:
        from kafka.admin import KafkaAdminClient
        admin = KafkaAdminClient(bootstrap_servers=brokers, request_timeout_ms=10000)
        return admin
    except Exception as exc:
        pytest.skip(f"Kafka broker not reachable: {exc}")
