"""Generated by vibe-rescue: PostgreSQL infrastructure validation tests.

These tests connect to the REAL PostgreSQL database and validate that the
schema matches what SQLAlchemy models expect. Run with --pro-mode flag.

Catches drift: model adds a column but migration was never applied,
table was dropped, FK constraint missing, nullable mismatch, etc.
"""
import pytest
from sqlalchemy import inspect as sa_inspect

# ADAPT: Import your SQLAlchemy models here
# from db.models import MyModel, AnotherModel

# ADAPT: List all models to validate against the database
MODELS = [
    # MyModel,
    # AnotherModel,
]


def _get_db_table_names(engine):
    """Get all table names from the real database."""
    db_inspector = sa_inspect(engine)
    return set(db_inspector.get_table_names())


def _get_db_columns(engine, table_name):
    """Get column details from the real database."""
    db_inspector = sa_inspect(engine)
    return {col["name"]: col for col in db_inspector.get_columns(table_name)}


def _get_db_pk(engine, table_name):
    """Get primary key column names from the real database."""
    db_inspector = sa_inspect(engine)
    pk = db_inspector.get_pk_constraint(table_name)
    return set(pk["constrained_columns"]) if pk else set()


def _get_db_fks(engine, table_name):
    """Get foreign key constraints from the real database."""
    db_inspector = sa_inspect(engine)
    return db_inspector.get_foreign_keys(table_name)


def _get_model_columns(model_class):
    """Get column names from the SQLAlchemy model."""
    mapper = sa_inspect(model_class)
    return {col.key for col in mapper.columns}


def _get_model_pk(model_class):
    """Get primary key column names from the SQLAlchemy model."""
    mapper = sa_inspect(model_class)
    return {col.name for col in mapper.primary_key}


def _get_model_fks(model_class):
    """Get foreign key targets from the SQLAlchemy model."""
    mapper = sa_inspect(model_class)
    fks = {}
    for col in mapper.columns:
        for fk in col.foreign_keys:
            fks[col.key] = fk.target_fullname
    return fks


# =============================================================================
# Table Existence
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_postgres
class TestInfraPostgresTablesExist:
    """Validate that every model table exists in the real database."""

    @pytest.mark.parametrize("model_class", MODELS, ids=lambda m: m.__name__)
    def test_infra_postgres_table_exists(self, pg_engine, model_class):
        # ADAPT: change pg_engine to your fixture name if different
        table_name = model_class.__tablename__
        db_tables = _get_db_table_names(pg_engine)
        assert table_name in db_tables, (
            f"Table '{table_name}' (model {model_class.__name__}) does not exist "
            f"in the database. Available tables: {sorted(db_tables)}"
        )


# =============================================================================
# Column Match
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_postgres
class TestInfraPostgresColumnsMatch:
    """Validate that every column in the model exists in the real table."""

    @pytest.mark.parametrize("model_class", MODELS, ids=lambda m: m.__name__)
    def test_infra_postgres_columns_match_model(self, pg_engine, model_class):
        table_name = model_class.__tablename__
        db_tables = _get_db_table_names(pg_engine)
        if table_name not in db_tables:
            pytest.skip(f"Table '{table_name}' does not exist -- skipping column check")

        model_cols = _get_model_columns(model_class)
        db_cols = set(_get_db_columns(pg_engine, table_name).keys())

        missing = model_cols - db_cols
        assert not missing, (
            f"Model {model_class.__name__} defines columns that are MISSING from "
            f"the real '{table_name}' table: {sorted(missing)}. "
            f"Likely cause: migration not applied. DB has: {sorted(db_cols)}"
        )


# =============================================================================
# Nullable Constraints
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_postgres
class TestInfraPostgresNullableMatch:
    """Validate that nullable constraints match between model and DB."""

    @pytest.mark.parametrize("model_class", MODELS, ids=lambda m: m.__name__)
    def test_infra_postgres_nullable_constraints_match(self, pg_engine, model_class):
        table_name = model_class.__tablename__
        db_tables = _get_db_table_names(pg_engine)
        if table_name not in db_tables:
            pytest.skip(f"Table '{table_name}' does not exist")

        mapper = sa_inspect(model_class)
        db_cols = _get_db_columns(pg_engine, table_name)
        mismatches = []

        for col in mapper.columns:
            if col.key not in db_cols:
                continue
            if col.primary_key:
                continue
            model_nullable = col.nullable
            db_nullable = db_cols[col.key].get("nullable", True)
            if model_nullable != db_nullable:
                mismatches.append(
                    f"  {col.key}: model={'nullable' if model_nullable else 'NOT NULL'}, "
                    f"db={'nullable' if db_nullable else 'NOT NULL'}"
                )

        assert not mismatches, (
            f"Nullable mismatches in {model_class.__name__} ({table_name}):\n"
            + "\n".join(mismatches)
        )


# =============================================================================
# Primary Keys
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_postgres
class TestInfraPostgresPrimaryKeys:
    """Validate that primary key constraints match."""

    @pytest.mark.parametrize("model_class", MODELS, ids=lambda m: m.__name__)
    def test_infra_postgres_primary_keys_match(self, pg_engine, model_class):
        table_name = model_class.__tablename__
        db_tables = _get_db_table_names(pg_engine)
        if table_name not in db_tables:
            pytest.skip(f"Table '{table_name}' does not exist")

        model_pk = _get_model_pk(model_class)
        db_pk = _get_db_pk(pg_engine, table_name)

        assert model_pk == db_pk, (
            f"Primary key mismatch in {model_class.__name__} ({table_name}): "
            f"model={sorted(model_pk)}, db={sorted(db_pk)}"
        )


# =============================================================================
# Foreign Keys
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_postgres
class TestInfraPostgresForeignKeys:
    """Validate that foreign key constraints exist in the real DB."""

    @pytest.mark.parametrize("model_class", MODELS, ids=lambda m: m.__name__)
    def test_infra_postgres_foreign_keys_exist(self, pg_engine, model_class):
        table_name = model_class.__tablename__
        db_tables = _get_db_table_names(pg_engine)
        if table_name not in db_tables:
            pytest.skip(f"Table '{table_name}' does not exist")

        model_fks = _get_model_fks(model_class)
        if not model_fks:
            pytest.skip(f"Model {model_class.__name__} has no foreign keys")

        db_fks = _get_db_fks(pg_engine, table_name)
        db_fk_cols = set()
        for fk in db_fks:
            db_fk_cols.update(fk["constrained_columns"])

        missing_fk_cols = set(model_fks.keys()) - db_fk_cols
        assert not missing_fk_cols, (
            f"Foreign key constraints missing in {model_class.__name__} ({table_name}): "
            f"model defines FKs on {sorted(model_fks.keys())} but DB only has FKs on "
            f"{sorted(db_fk_cols)}. Missing: {sorted(missing_fk_cols)}"
        )


# =============================================================================
# Orphaned Column Detection (warn only)
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_postgres
class TestInfraPostgresExtraDbColumns:
    """Detect columns in DB that are NOT in the model (possible orphaned columns)."""

    @pytest.mark.parametrize("model_class", MODELS, ids=lambda m: m.__name__)
    def test_infra_postgres_no_orphaned_columns(self, pg_engine, model_class):
        table_name = model_class.__tablename__
        db_tables = _get_db_table_names(pg_engine)
        if table_name not in db_tables:
            pytest.skip(f"Table '{table_name}' does not exist")

        model_cols = _get_model_columns(model_class)
        db_cols = set(_get_db_columns(pg_engine, table_name).keys())

        extra = db_cols - model_cols
        if extra:
            import warnings
            warnings.warn(
                f"Table '{table_name}' has columns not in model {model_class.__name__}: "
                f"{sorted(extra)}. These may be orphaned or managed outside SQLAlchemy.",
                stacklevel=2,
            )
