"""Generated by vibe-rescue: Kafka infrastructure validation tests.

These tests connect to the REAL Kafka broker and validate that all topics
referenced in consumer/producer config exist. Run with --pro-mode flag.

Catches: topic not created, topic name typo, broker unreachable,
consumer group issues, missing produced topics.
"""
import pytest
import re
from pathlib import Path


SERVICE_ROOT = Path(__file__).parent.parent

# ADAPT: List all topics consumed by your service
CONSUMED_TOPICS = [
    # "my-service-events-v1",
    # "my-service-orders-v1",
]

# ADAPT: List produced topic base constants (topics constructed dynamically)
PRODUCED_TOPIC_BASES = [
    # "my-service-output-base",
]

# ADAPT: Set the expected total consumed topic count for sanity check
EXPECTED_CONSUMED_TOPIC_COUNT = 0  # ADAPT: your count

# ADAPT: Regex pattern for your topic naming convention
TOPIC_NAMING_PATTERN = re.compile(
    r"^[a-z][a-z0-9-]*$"  # ADAPT: your topic naming regex, or auto-set from memory.yaml
)

# ADAPT: Path to your consumer config file (for config alignment tests)
CONSUMER_CONFIG_PATH = SERVICE_ROOT / "consumers" / "consumer_config.py"  # ADAPT


def _get_broker_topics(kafka_admin):
    """List all topics in the Kafka broker."""
    return set(kafka_admin.list_topics())


def _ensure_topics_exist(kafka_admin, topics):
    """Create topics if they don't exist (for auto.create.topics.enable=false)."""
    try:
        from kafka.admin import NewTopic
        existing = _get_broker_topics(kafka_admin)
        missing = [t for t in topics if t not in existing]
        if missing:
            new_topics = [
                NewTopic(name=t, num_partitions=1, replication_factor=1)
                for t in missing
            ]
            kafka_admin.create_topics(new_topics=new_topics, validate_only=False)
        return missing
    except Exception:
        return []


# =============================================================================
# Broker Connectivity
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_kafka
class TestInfraKafkaBrokerConnectivity:
    """Validate Kafka broker is reachable and functional."""

    def test_infra_kafka_broker_is_reachable(self, kafka_admin):
        topics = _get_broker_topics(kafka_admin)
        assert isinstance(topics, set), "Failed to list topics from broker"

    def test_infra_kafka_broker_cluster_info(self, kafka_admin):
        metadata = kafka_admin.describe_cluster()
        assert metadata is not None, "Could not retrieve cluster metadata"


# =============================================================================
# Consumed Topics Exist
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_kafka
class TestInfraKafkaConsumedTopicsExist:
    """Validate all consumed topics exist in the broker."""

    @pytest.fixture(autouse=True)
    def _ensure_all_topics(self, kafka_admin):
        """Pre-create all consumed topics to validate naming contract."""
        _ensure_topics_exist(kafka_admin, CONSUMED_TOPICS)

    @pytest.mark.parametrize("topic", CONSUMED_TOPICS)
    def test_infra_kafka_consumed_topic_exists(self, kafka_admin, topic):
        topics = _get_broker_topics(kafka_admin)
        assert topic in topics, (
            f"Consumed topic '{topic}' does not exist in Kafka broker. "
            f"This consumer will fail to start."
        )


# =============================================================================
# Produced Topic Bases Are Valid
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_kafka
class TestInfraKafkaProducedTopicBases:
    """Validate that produced topic base constants are correct and usable."""

    @pytest.mark.parametrize("base", PRODUCED_TOPIC_BASES)
    def test_infra_kafka_produced_topic_base_can_create(self, kafka_admin, base):
        """Verify that a dynamically constructed topic can be created."""
        test_topic = f"{base}-test-validation"
        _ensure_topics_exist(kafka_admin, [test_topic])
        topics = _get_broker_topics(kafka_admin)
        assert test_topic in topics, (
            f"Failed to create topic '{test_topic}' from base '{base}'"
        )


# =============================================================================
# Topic Naming Convention
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_kafka
class TestInfraKafkaTopicNamingConvention:
    """Validate topic naming follows the expected pattern."""

    @pytest.mark.parametrize("topic", CONSUMED_TOPICS)
    def test_infra_kafka_topic_name_follows_convention(self, topic):
        assert TOPIC_NAMING_PATTERN.match(topic), (
            f"Topic '{topic}' does not match expected naming convention"
        )


# =============================================================================
# Consumer Config Alignment
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_kafka
class TestInfraKafkaConsumerConfigAlignment:
    """Validate consumer config file topics match what's in the broker."""

    def test_infra_kafka_all_config_topics_exist_in_broker(self, kafka_admin):
        """Every active topic in the consumer config must exist in broker."""
        if not CONSUMER_CONFIG_PATH.exists():
            pytest.skip(f"Consumer config file not found: {CONSUMER_CONFIG_PATH}")

        content = CONSUMER_CONFIG_PATH.read_text()
        active_topics = set()
        for line in content.split("\n"):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            matches = re.findall(r'"([a-z][-a-z0-9_.]+)"', stripped)  # ADAPT: adjust regex to match your topic string pattern
            active_topics.update(matches)

        _ensure_topics_exist(kafka_admin, list(active_topics))
        broker_topics = _get_broker_topics(kafka_admin)
        missing = active_topics - broker_topics
        assert not missing, (
            f"Topics in consumer config not found in broker: {sorted(missing)}"
        )

    def test_infra_kafka_consumed_topic_count_matches(self, kafka_admin):
        """Sanity check: number of consumed topics matches expected count."""
        if EXPECTED_CONSUMED_TOPIC_COUNT == 0:
            pytest.skip("EXPECTED_CONSUMED_TOPIC_COUNT not configured (set to 0)")

        if not CONSUMER_CONFIG_PATH.exists():
            pytest.skip(f"Consumer config file not found: {CONSUMER_CONFIG_PATH}")

        content = CONSUMER_CONFIG_PATH.read_text()
        active_topics = set()
        for line in content.split("\n"):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            matches = re.findall(r'"([a-z][-a-z0-9_.]+)"', stripped)  # ADAPT: adjust regex to match your topic string pattern
            active_topics.update(matches)

        assert len(active_topics) == EXPECTED_CONSUMED_TOPIC_COUNT, (
            f"Expected {EXPECTED_CONSUMED_TOPIC_COUNT} consumed topics, "
            f"found {len(active_topics)}: {sorted(active_topics)}"
        )
