"""Generated by vibe-rescue: ClickHouse infrastructure validation tests.

These tests connect to the REAL ClickHouse database and validate that tables
and columns referenced in code/migrations actually exist. Run with --pro-mode.

Catches drift: migration not applied, table dropped, column renamed,
distributed table missing, etc.
"""
import pytest


# ADAPT: List tables your service queries or inserts into
BASE_TABLES = [
    # "my_table",
    # "another_table",
]

# ADAPT: List distributed table variants (warn-only if missing in single-node Docker)
DISTRIBUTED_TABLES = [
    # "distributed_my_table",
]

# ADAPT: List materialized views (warn-only if missing)
MATERIALIZED_VIEWS = [
    # "mv_my_view",
]

# ADAPT: Map table -> expected column set
EXPECTED_COLUMNS = {
    # "my_table": {"col1", "col2", "col3"},
}

# ADAPT: Map table -> {column: expected_type} for type validation
EXPECTED_COLUMN_TYPES = {
    # "my_table": {"col1": "UInt16", "col2": "String"},
}

# ADAPT: Set your ClickHouse database name
CH_DATABASE = "ccp_ril"  # ADAPT: your database name


def _get_ch_tables(ch_client):
    """Get all table/view names in the database."""
    rows = ch_client.execute(
        f"SELECT name FROM system.tables WHERE database = '{CH_DATABASE}'"
    )
    return {row[0] for row in rows}


def _get_ch_columns(ch_client, table_name):
    """Get column names and types for a table."""
    rows = ch_client.execute(
        "SELECT name, type FROM system.columns "
        "WHERE database = %(db)s AND table = %(table)s",
        {"db": CH_DATABASE, "table": table_name},
    )
    return {row[0]: row[1] for row in rows}


# =============================================================================
# Base Tables (must exist)
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_clickhouse
class TestInfraClickHouseBaseTablesExist:
    """Validate that base tables exist."""

    @pytest.mark.parametrize("table_name", BASE_TABLES)
    def test_infra_clickhouse_base_table_exists(self, ch_client, table_name):
        tables = _get_ch_tables(ch_client)
        assert table_name in tables, (
            f"ClickHouse table '{CH_DATABASE}.{table_name}' does not exist. "
            f"Check if migration was applied. Available tables: {sorted(tables)}"
        )


# =============================================================================
# Distributed Tables (warn if missing in single-node)
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_clickhouse
class TestInfraClickHouseDistributedTables:
    """Validate distributed tables (may be absent in single-node Docker)."""

    @pytest.mark.parametrize("table_name", DISTRIBUTED_TABLES)
    def test_infra_clickhouse_distributed_table_exists(self, ch_client, table_name):
        tables = _get_ch_tables(ch_client)
        if table_name not in tables:
            import warnings
            warnings.warn(
                f"Distributed table '{CH_DATABASE}.{table_name}' not found. "
                f"Expected in multi-node clusters. Single-node Docker may skip this.",
                stacklevel=2,
            )
            pytest.skip(
                f"Distributed table '{table_name}' not available in single-node mode"
            )


# =============================================================================
# Materialized Views
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_clickhouse
class TestInfraClickHouseMaterializedViews:
    """Validate materialized views exist."""

    @pytest.mark.parametrize("view_name", MATERIALIZED_VIEWS)
    def test_infra_clickhouse_materialized_view_exists(self, ch_client, view_name):
        tables = _get_ch_tables(ch_client)
        if view_name not in tables:
            import warnings
            warnings.warn(
                f"Materialized view '{CH_DATABASE}.{view_name}' not found. "
                f"This may affect data pipelines.",
                stacklevel=2,
            )
            pytest.skip(f"Materialized view '{view_name}' not available")


# =============================================================================
# Column Validation
# =============================================================================

@pytest.mark.infra
@pytest.mark.infra_clickhouse
class TestInfraClickHouseColumnValidation:
    """Validate columns match expected schema from migrations."""

    @pytest.mark.parametrize("table_name", [t for t in EXPECTED_COLUMNS])
    def test_infra_clickhouse_table_has_all_columns(self, ch_client, table_name):
        tables = _get_ch_tables(ch_client)
        if table_name not in tables:
            pytest.skip(f"{table_name} table does not exist")

        db_cols = set(_get_ch_columns(ch_client, table_name).keys())
        expected = EXPECTED_COLUMNS[table_name]
        missing = expected - db_cols
        assert not missing, (
            f"{table_name} is missing columns: {sorted(missing)}. "
            f"DB has: {sorted(db_cols)}"
        )

    @pytest.mark.parametrize("table_name", [t for t in EXPECTED_COLUMN_TYPES])
    def test_infra_clickhouse_column_types_match(self, ch_client, table_name):
        tables = _get_ch_tables(ch_client)
        if table_name not in tables:
            pytest.skip(f"{table_name} table does not exist")

        col_types = _get_ch_columns(ch_client, table_name)
        expected_types = EXPECTED_COLUMN_TYPES[table_name]
        mismatches = []
        for col, expected_type in expected_types.items():
            if col in col_types and col_types[col] != expected_type:
                mismatches.append(
                    f"  {col}: expected={expected_type}, actual={col_types[col]}"
                )
        assert not mismatches, (
            f"{table_name} column type mismatches:\n" + "\n".join(mismatches)
        )
